/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DishService } from "../dish.service";
import { DishCreateInput } from "./DishCreateInput";
import { Dish } from "./Dish";
import { DishFindManyArgs } from "./DishFindManyArgs";
import { DishWhereUniqueInput } from "./DishWhereUniqueInput";
import { DishUpdateInput } from "./DishUpdateInput";

export class DishControllerBase {
  constructor(protected readonly service: DishService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Dish })
  async createDish(@common.Body() data: DishCreateInput): Promise<Dish> {
    return await this.service.createDish({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Dish] })
  @ApiNestedQuery(DishFindManyArgs)
  async dishes(@common.Req() request: Request): Promise<Dish[]> {
    const args = plainToClass(DishFindManyArgs, request.query);
    return this.service.dishes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Dish })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dish(
    @common.Param() params: DishWhereUniqueInput
  ): Promise<Dish | null> {
    const result = await this.service.dish({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Dish })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDish(
    @common.Param() params: DishWhereUniqueInput,
    @common.Body() data: DishUpdateInput
  ): Promise<Dish | null> {
    try {
      return await this.service.updateDish({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Dish })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDish(
    @common.Param() params: DishWhereUniqueInput
  ): Promise<Dish | null> {
    try {
      return await this.service.deleteDish({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
